services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    volumes:
      - ./api:/app
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - api
