# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "grape", "~> 2.0"
gem "grape-roar", "~> 0.4.0"
gem "grape_logging", "~> 1.8"
gem "grape-swagger", "~> 2.0.0"
gem "grape-entity", "~> 1.0.0"
gem "roar", "~> 1.1"
gem "redis", "~> 5.0"
gem "activesupport", "~> 7.1"
gem "pubnub", "~> 5.2"
gem "rack-cors", "~> 2.0"
gem "pg", "~> 1.5"
gem "sequel", "~> 5.74"
gem "sequel_pg", "~> 1.17"
gem "bcrypt", "~> 3.1"
gem "rake", "~> 13.0"

gem "rack", "~> 2.2"
gem "rackup", "~> 1.0.0"
gem "webrick", "~> 1.8"

# Development and testing
group :development do
  gem "guard", "~> 2.18"
  gem "guard-rack", "~> 2.2"
end
