# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "grape", "~> 2.0"
gem "grape-roar", "~> 0.4.0"
gem "grape_logging", "~> 1.8"
gem "grape-swagger", "~> 2.0.0"
gem "roar", "~> 1.1"
gem "redis", "~> 5.0"
gem "activesupport", "~> 7.1"
gem "pubnub", "~> 5.2"
gem "rack-cors", "~> 2.0"

gem "rack", "~> 3.1"
gem "rackup", "~> 2.1"
